import sys
infile = open("R1_list")   # the list of the idr sequence data files

for line in infile:
        name = line.strip().split('\n')[0]
        out = open((name + "idr_hg38.sh"), "w")

        out.write("#! /bin/bash\n#$ -N %s_entire.IDR.pipe\n#$ -pe openmp 1\n#$ -q som,sam,bio,pub64\n\n"%(name))
        out.write("# NEED TO CHANGE NAMES OF TXT FILES AND TAG DIRECTORIES BEFORE STARTING THIS SCRIPT, PLACE IN NEW DIRECTORY (CALLED rename)\n\n")
        out.write("module load R/3.4.1\nmodule load bowtie/1.0.0\nmodule load samtools/1.3\nmodule load homer/4.7\nmodule load picard-tools/1.96\n\n")
        out.write("#module load R/3.1.3\n# -------------------------------------\n# Note:\n# -----------------------------------------\n# IDR code runs only with python3. Use Anaconda3 python by setting path in the .bashrc file\n# ---------------------------------------\n# Copy required scripts and code to this folder\n# --------------------------------\n")
        out.write("tagPATH='/share/samdata/crwilcox/ATAC_pooled/Donovan/ATAC_1902/rename'\n")
        out.write("p500='%s_500'\n"%(name))
        out.write("p150='%s_150'\n"%(name))
        out.write("peaksPATH='peaks/replicates'\n")
        out.write("\n")
        out.write("#make directories for 150 and 500 lengths for each replicate\nmkdir $p500\nmkdir $p150\n")
        out.write("cp -r /share/samdata/rmurad/DrMomand/code/idr-code/homer-idr/idr/* $p150/.\ncp -r /share/samdata/rmurad/DrMomand/code/idr-code/homer-idr/idr/* $p500/.\n# Copy the peaks for each replicate into one folder\n# ------------------------------\n")
        out.write("mkdir -p $p500/$peaksPATH/\nmkdir -p $p150/$peaksPATH/\n")
        out.write("cp $tagPATH/%s_1_ATAC_tagdir150.txt $p150/$peaksPATH/%s_1_ATAC_tagdir150.txt\ncp $tagPATH/%s_1_ATAC_tagdir500.txt $p500/$peaksPATH/%s_1_ATAC_tagdir500.txt\n"%(name,name,name,name))
        out.write("cp $tagPATH/%s_2_ATAC_tagdir150.txt $p150/$peaksPATH/%s_2_ATAC_tagdir150.txt\ncp $tagPATH/%s_2_ATAC_tagdir500.txt $p500/$peaksPATH/%s_2_ATAC_tagdir500.txt\n"%(name,name,name,name))
        out.write("cp $tagPATH/%s_3_ATAC_tagdir150.txt $p150/$peaksPATH/%s_3_ATAC_tagdir150.txt\ncp $tagPATH/%s_3_ATAC_tagdir500.txt $p500/$peaksPATH/%s_3_ATAC_tagdir500.txt\n"%(name,name,name,name))
        out.write("# Make a combined tag directory for all reps, find peaks for pooled combined\n# ------------------------\n")
        out.write("# --------------------------\n#  Set up idr for 150bp\n# -----------------------\n")
        out.write("cd $p150/\n")
        out.write("makeTagDirectory Combined -d $tagPATH/%s_1_ATAC_tagdir150 $tagPATH/%s_2_ATAC_tagdir150 $tagPATH/%s_3_ATAC_tagdir150\n"%(name,name,name))
        out.write("cd Combined\nfindPeaks ./ -LP .1 -poisson .1 -style factor -size 150 -minDist 50 -localSize 50000 -o %s_combined.peaks.txt\ncd ../\n"%(name))
        out.write("# ---------------------------\n# Create pseudoreps for individual reps (Step 5)\n# -----------------------------\n") 
        out.write("mkdir -p pseudoreps/individual\n")
        out.write("python run_idr.py pseudoreplicate -d $tagPATH/%s_1_ATAC_tagdir150 $tagPATH/%s_2_ATAC_tagdir150 $tagPATH/%s_3_ATAC_tagdir150 -o pseudoreps/individual\n"%(name,name,name))
        out.write("# ---------------------------\n# Create pseudoreps for pooled (Step6)\n# --------------------------\n")
        out.write("mkdir -p pseudoreps/pooled\npython run_idr.py pseudoreplicate -d Combined -o pseudoreps/pooled\n")
        out.write("# --------------------------\n# Call peaks for individual pseudoreps (Step 7)\n# ----------------------\n")
        out.write("mkdir -p peaks/pseudoreps\ncd peaks/pseudoreps\nfor f in ../../pseudoreps/individual/*\n        do\n        findPeaks $f -LP .1 -poisson .1 -style factor -size 150 -minDist 50 -localSize 50000 -o ${f}_peaks.txt\n        done\ncd ../../\n")
        out.write("# --------------------------\n# Call peaks for combined pseudoreps (Step 8)\n# -----------------------\n")
        out.write("mkdir -p peaks/pooled-pseudoreps\ncd peaks/pooled-pseudoreps\nfor f in ../../pseudoreps/pooled/*\n        do\n        findPeaks $f -LP .1 -poisson .1 -style factor -size 150 -minDist 50 -localSize 50000 -o ${f}_peaks.txt\n        done\ncd ../../\n")
        out.write("# --------------------------\n# Finally run IDR (Step 9)\n# ------------------------\n")
        out.write("cp pseudoreps/individual/*peaks.txt peaks/pseudoreps/\ncp pseudoreps/pooled/*peaks.txt peaks/pooled-pseudoreps/\npython  run_idr.py idr -p peaks/replicates/*  -pr peaks/pseudoreps/* -ppr peaks/pooled-pseudoreps/* --pooled_peaks Combined/%s_combined.peaks.txt  -o idr-output --threshold .01\n"%(name))
        out.write("cd ../\n")
        out.write("# --------------------------\n# Do the same for 500bp\n# -----------------------\n") 
        out.write("cd $p500/\n")
        out.write("makeTagDirectory Combined -d $tagPATH/%s_1_ATAC_tagdir500 $tagPATH/%s_2_ATAC_tagdir500 $tagPATH/%s_3_ATAC_tagdir500\n"%(name,name,name))
        out.write("cd Combined\nfindPeaks ./ -LP .1 -poisson .1 -style factor -size 500 -minDist 50 -localSize 50000 -o %s_combined.peaks.txt\ncd ../\n"%(name))
        out.write("# ---------------------------\n# Create pseudoreps for individual reps (Step 5)\n# -----------------------------")       
        out.write("mkdir -p pseudoreps/individual\n")
        out.write("python run_idr.py pseudoreplicate -d $tagPATH/%s_1_ATAC_tagdir500 $tagPATH/%s_2_ATAC_tagdir500 $tagPATH/%s_3_ATAC_tagdir500 -o pseudoreps/individual\n"%(name,name,name))
        out.write("# ---------------------------\n# Create pseudoreps for pooled (Step6)\n# --------------------------\n")
        out.write("mkdir -p pseudoreps/pooled\npython run_idr.py pseudoreplicate -d Combined -o pseudoreps/pooled\n")
        out.write("# --------------------------\n# Call peaks for individual pseudoreps (Step 7)\n# ----------------------\n")
        out.write("mkdir -p peaks/pseudoreps\ncd peaks/pseudoreps\nfor f in ../../pseudoreps/individual/*\n        do\n        findPeaks $f -LP .1 -poisson .1 -style factor -size 500 -minDist 50 -localSize 50000 -o ${f}_peaks.txt\n        done\ncd ../../\n")
        out.write("# --------------------------\n# Call peaks for combined pseudoreps (Step 8)\n# -----------------------\n")
        out.write("mkdir -p peaks/pooled-pseudoreps\ncd peaks/pooled-pseudoreps\nfor f in ../../pseudoreps/pooled/*\n        do\n        findPeaks $f -LP .1 -poisson .1 -style factor -size 500 -minDist 50 -localSize 50000 -o ${f}_peaks.txt\n        done\ncd ../../\n")
        out.write("# --------------------------\n# Finally run IDR (Step 9)\n# ------------------------\n")
        out.write("cp pseudoreps/individual/*peaks.txt peaks/pseudoreps/\ncp pseudoreps/pooled/*peaks.txt peaks/pooled-pseudoreps/\npython  run_idr.py idr -p peaks/replicates/* -pr peaks/pseudoreps/* -ppr peaks/pooled-pseudoreps/* --pooled_peaks Combined/%s_combined.peaks.txt  -o idr-output --threshold .01\n"%(name))
        out.close()

